### ISSUE TITLE
tidy freeny data set

### ISSUE THREAD

**Issue by mackie90125** [jayhesselberth/tidy_datasets#3]
While I was attempting to tidy the freeny(.x.y) datasets, I got the following error message from the `gather()` function:

```
Warning message:
attributes are not identical across measure variables; they will be dropped
```

Here is the code I ran (which is likely not the most efficient way to go about this).

``` r
freeny_y_df <- as.data.frame(t(matrix(c(NA,freeny.y), 4)))

colnames(freeny_y_df) <- c("Qtr1","Qtr2","Qtr3","Qtr4")
rownames(freeny_y_df) <- 1962:1971

freeny_y_tmp <- freeny_y_df %>% mutate(year = rownames(freeny_y_df)) %>%
  gather(Qtr, value, -year) %>%
  arrange(year)

freeny_y_tidy <- freeny_y_tmp[2:40,]

freeny_tidy <- freeny %>% mutate(year = freeny_y_tidy$year, Qtr = freeny_y_tidy$Qtr) %>%
  gather(exp_var, value, -year, -Qtr)
## this is the gather that produces an error
head(freeny_tidy)
```

This appears to have worked. It turns 5 columns of length 39, into 1 column of length 195. So I'm not sure what the error message means.

**Comment by jayhesselberth** [comment]
You need to add a surrogate observation column:

``` R
freeny %>%
  dplyr::mutate(yearqtr = rownames(.),
                obs = dplyr::row_number()) %>%
  tidyr::gather(key, value, -obs)
```

**Comment by jayhesselberth** [comment]
I missed the `freeny.x` and `freeny.y` datasets. My [`tidytime`](https://github.com/jayhesselberth/tidytime) library might be useful for the `x` dataset.

**Comment by mackie90125** [comment]
For some reason R will not let me run your code because row_number is missing an argument. I also added `-yearqtr` to gather.

``` r
freeny %>%
  dplyr::mutate(yearqtr = rownames(.),
                obs = 1:39) %>%
  tidyr::gather(key, value, -obs, -yearqtr)
```

Anyway, I get the same error when I run this as well. But in the end, the key and value column produced by your code and by mine are identical. So I'm just not going to worry about this error.

**Comment by jayhesselberth** [comment]
FWIW, hard coding `1:39` is not a very general solution to the problem. The following works for me.

``` R
library(tidyr)
library(dplyr)

freeny %>%
  mutate(yearqtr = rownames(.),
         obs = row_number()) %>%
  gather(key, value, -obs) %>%
  arrange(obs)

```

**Comment by mackie90125** [comment]
Thanks for your help Jay.

row_number is now working for me. I don't know why it wasn't before.
